### ISSUE TITLE
The username isn't derived by the filename anymore

### ISSUE THREAD

**Issue by aventrax** [dannyvankooten/browserpass#130] opened 2017-09-15 11:26 UTC
The extension fills only the password and not the username that should be derived by the filename.
The structure is /web/my.site.com/username and my .gpg file contains only the password.
Modifying the .gpg file adding "login:username" before the password solves the issue.

The issue come out today after compiling the last version of browserpass on windows with msys2, I have another installation of browserpass on linux, compiled few weeks ago, that is not affected by this issue so I think this bug has been introduced recently.

@chrboe confirmed this behavoir on the #25

**Comment by chrboe** [comment] 2017-09-15 11:34
There is a function that should handle this (see [here](https://github.com/dannyvankooten/browserpass/blob/master/browserpass.go#L161)), however just from looking at the code it seems like that should get parsed just fine.

Maybe the extension itself (ass opposed to the backend) is to blame for this (#101 got merged very recently and has something to do with the username input field). I'll bisect to figure out where it's coming from.

**Comment by maximbaz** [comment] 2017-09-15 11:48
The frontend code has changed a lot, and I don't have rights to update browser extensions in stores (see #117).

The only way to use it for now is to clone master, and do:

```
$ cd browserpass
$ yarn
$ make js
```

And then load `browserpass/chrome` as `Load unpacked extension` in `chrome://extensions`.

If this still does not fix the issue for you, could you share examples of particular websites where you see the issue? I've tried on github.com and a few others, login is being inserted just fine.

**Comment by aventrax** [comment] 2017-09-15 11:48
Sorry, I'm on firefox, what about you? Is it worth to try even the chrome extension (maybe it behave differently)?

**Comment by chrboe** [comment] 2017-09-15 11:51
@maximbaz Am I correct in assuming that you're using Linux? Unfortunately I don't have a Linux PC at hand right now, so I'm not sure whether or not this bug actually occurs on Linux. Can you confirm?

(I'm using Chrome on Windows right now btw and the bug happens, so I suspect it's either a regression or it has something to do with Windows in general)

**Comment by maximbaz** [comment] 2017-09-15 11:53
I'm using Chromium on Linux, and I don't reproduce this issue. But there were changes in frontend that affect this behavior, maybe you just caught a particular website where there is a regression. Do you reproduce this on https://github.com/login ?

**Comment by aventrax** [comment] 2017-09-15 11:54
I can compile the last browserpass this evening at home (Linux) to see if the issue is present.
Yes, the issue is present on github login as well on nextcloud login.

**Comment by chrboe** [comment] 2017-09-15 11:57
I originally tried on the Gitlab login page, but I can confirm that GitHub behaves the same.

I guess I'll have to figure out a way to build the extension on Windows then :)

**Comment by chrboe** [comment] 2017-09-15 12:26
~~Alright, since c6736a999ae0932c7907b2b4108a6a3473806f4b (the windows compatibility PR) is the last revision I can comfortably bisect from, and this bug appears there, I'll just assume it was always there (remember, hardly anyone really ever ran this on Windows).~~

~~If anyone with a Windows machine could confirm whether this is a bug in the back- or the fronte~~

Hold on, I just figured it out! The function I mentioned earlier ([link](https://github.com/dannyvankooten/browserpass/blob/master/browserpass.go#L161)) assumes a forward slash in the filename, which obviously doesn't exist on windows (d'oh). I guess I must have missed that when I "ported" the code.

Anyways, just replacing the `/` by `os.PathSeperator` should do the trick I think.

**Comment by maximbaz** [comment] 2017-09-15 12:32
Nice job! Please send a quick PR :D

**Closed** 2017-09-15 12:44 UTC

**Comment by maximbaz** [comment] 2017-09-15 12:46
@chrboe thanks once again :+1: 

@aventrax try the latest master, should work now 😉

**Comment by aventrax** [comment] 2017-09-15 12:50
Working. Nice job, very active development :-D
