### ISSUE TITLE
Chrome extension not filling in passwords

### ISSUE THREAD

**Issue by mnussbaum** [dannyvankooten/browserpass#28] opened 2017-01-07 00:30 UTC
browserpass 1.0.3
Chrome: Version 55.0.2883.95 (64-bit)
macOS: 10.11.6-x86_64
pass: 1.6.5

When I go to login to a site using browserpass, the extension correctly detects that the password for the current site is stored in pass, and lists it in the extension drop down. When I click the site name in the drop down the extension displays a spinning wheel and never fills in the username and password of the site.

Tested on both github and twitter login pages. 

Happy to help debug if there's anything you'd like me to try!

Edit: Looking in the Chrome inspector for the extension I see `Native host has exited` being logged, I believe from https://github.com/dannyvankooten/browserpass/blob/master/chrome/script.browserify.js#L99. However I've run `install.sh` and confirmed that the native messaging hosts entry for browserpass has the correct, executable path, and the right chrome extension ID.

**Comment by dannyvankooten** [comment] 2017-01-07 10:29
Hey @mnussbaum,

It sounds like the "native host" (the binary) is failing in the step that occurs right before filling the password, retrieving the password from the clicked pass file. Could it be that you're on a later version of the Chrome extension with an earlier version of the binary? If you download the latest binary from the [releases tab](https://github.com/dannyvankooten/browserpass/releases) then I believe you should be good to go!

**Comment by eivindbergem** [comment] 2017-01-15 10:23
I have the same setup and problem as @mnussbaum. I've made sure to use the latest binary, but the problem remains.

I get the following error message in the inspector console:

```
Error in event handler for (unknown): TypeError: Cannot read property 'p' of undefined
    at fillLoginForm (chrome-extension://jegbgfamcgeocbfeebacnkociplhmfbk/script.js:167:65)
    at chrome-extension://jegbgfamcgeocbfeebacnkociplhmfbk/script.js:131:5
```

**Comment by jxs** [comment] 2017-01-17 17:22
having the same problem:
```
Error in event handler for (unknown): TypeError: Cannot read property 'p' of undefined
    at fillLoginForm (chrome-extension://klfoddkbhleoaabpmiigbmpbjfljimgb/script.js:167:65)
    at chrome-extension://klfoddkbhleoaabpmiigbmpbjfljimgb/script.js:131:5
```

**Comment by compuguy** [comment] 2017-01-23 21:24
Having same problems as well
browserpass: 1.0.3
Chrome:  55.0.2883.95 (64-bit)
macOS: 10.12.2

> Error in event handler for (unknown): TypeError: Cannot read property 'p' of undefined
>     at fillLoginForm (chrome-extension://jegbgfamcgeocbfeebacnkociplhmfbk/script.js:167:65)
>     at chrome-extension://jegbgfamcgeocbfeebacnkociplhmfbk/script.js:131:5

**Comment by emilecantin** [comment] 2017-01-24 17:16
It looks like the latest version from the Chrome Web Store is 1.0.3, but the latest release from the "releases" tab is 1.0.2.

Could it be related?

**Comment by compuguy** [comment] 2017-01-24 19:04
@emilecantin Maybe, but it looks like the versioning for the chrome app is separate from the chrome messaging binary.

**Comment by emilecantin** [comment] 2017-01-24 19:10
For what it's worth, I just installed everything this morning for the first
time (saw it mentioned on Hacher News), and I had this issue, so a fresh
install is probably a good way to reproduce it.

Le mar. 24 janv. 2017 à 14:04, Alex Hall <notifications@github.com> a
écrit :

**Comment by dannyvankooten** [comment] 2017-01-24 19:39
Hey everyone,

Thanks for the heads up, I'll try to see if I can reproduce it with a fresh install. You're running the latest stable Chrome right, no nightly or anything? 

Will most likely have time for this on Friday, so it'll be a few days, sorry.

**Comment by emilecantin** [comment] 2017-01-24 19:43
Yes, the latest stable Chrome (Version 55.0.2883.95 (64-bit)) on OS X
10.11.6

**Comment by dsgh** [comment] 2017-02-01 16:51
Hi, I'm having the same issue, both with Chrome 55 and 56. I've made some experiments with the gpg agent environment variables; and after a lot of experimentation it seems that the issue is not in the step of filling the password, but in the step of "communicating" with the gpg agent.

It apparently is only working when the browser (I've tested in both Chrome and Firefox) is started from the console, ie `open -a "Google Chrome"`, and it's not working when the browser is started from finder or launcher. This is independent of whether the environment variables are there or not (ie, in the console, if they are set it will use that, otherwise it will start a new agent; and outside of the console, whether they are set with `launchctl setenv GPG_AGENT_INFO ...` or not, it doesn't connect and is not able to start a new agent).

@mnussbaum how can I see the logs on the "Chrome inspector for the extension"? Is this something I have to enable? I don't see anything on the 'regular' devtools for the site I am in.

**Comment by lherich** [comment] 2017-02-01 18:02
@dsgh:
I can confirm your  observation. After starting Chrome from the console the auto fill does work as expected. Starting via Launcher the browserpass extensions shows the file/dir structure from pass, however the auto fill does not work.
macOS Sierra 10.12.2
Google Chrome Version 55.0.2883.95 (64-bit)

**Comment by mnussbaum** [comment] 2017-02-06 02:27
> @mnussbaum how can I see the logs on the "Chrome inspector for the extension"?
 
@dsgh there's probably a better way, but what I do is open the browserpass dropdown in Chrome, right click it, click "Inspect".

**Comment by tylershuster** [comment] 2017-02-07 18:45
I'm having the same problem with the same symptoms and error messages. I primarily use Firefox (where I don't know how to inspect the extension like in Chrome) and the symptoms are the same there.

**Comment by dannyvankooten** [comment] 2017-02-10 12:25
Can someone please try manually building the Browserpass binary with 343722bee3bfff3739caceee74d2a543505d8cd5 to see if that fixes anything? It invokes the gpg command directly instead of invoking pass.

If it still doesn't trigger the GPG agent, can you please invoke Chrome from the command line using:

```
google-chrome --enable-logging --v=1
```

That should enable logging and show all logging statements from Browserpass too which would be super helpful here. :)

**Comment by tylershuster** [comment] 2017-02-10 16:50
I did the above (AFAIK) and the terminal said `exec: "pass": executable file not found in $PATH` so I symlinked `gopass` to `pass` and it worked. (Well, it filled and submitted when I was on the login page but I couldn't retrieve from an arbitrary page; not sure if that's intended behavior)

**Comment by quulah** [comment] 2017-02-10 18:35
Tried with 343722b first, but that had the trailing slash bug. :)

Any way, now with the master, it works the same way as the others stated earlier.

When starting from the console it fills in the credentials, but when launching from the launcher it doesn't work.

**Comment by SamHH** [comment] 2017-02-20 12:33
Same here by the way. Latest binary, latest extension from web store, Chrome, macOS. It lists the usernames but when I click on one it just gets stuck on loading spinner. Console output of the extension is an object with `Native host has exited.` plus the `Cannot read property 'p' of undefined` error that others saw above.

One thing that needs adding after this is resolved is some better error handling to inform the user that there was an error without needing to check the extension's console.

**Comment by sibte** [comment] 2017-03-24 16:46
I have the same issue with the loading spinner if I launch Chromium from e.g. the dock on OS X. However, if I launch Chromium from the command line, it works as expected. I suspect some environmental values not being passed / present when invoking Chromium from e.g. the dock.

**Comment by dannyvankooten** [comment] 2017-04-10 07:05
Duplicate of #13.

**Closed** 2017-04-10 07:05 UTC
Labels: bug, duplicate
