### ISSUE TITLE
Support for generating passwords

### ISSUE THREAD

**Issue by ohthehugemanatee** [dannyvankooten/browserpass#118] opened 2017-08-16 12:32 UTC
Ideally a context menu action "Generate and fill a password" for form fields. Uses pass' generation to create the random string, and saves it in the extension's own format.

**Comment by bddenhartog** [comment] 2017-09-15 04:11
@ohthehugemanatee  said:

> Uses pass' generation to create the random string, and saves it in the extension's own format.

`browserpass` no longer depends on `pass`. It uses `gpg` directly for [various reasons](https://github.com/dannyvankooten/browserpass/issues/6).

**Comment by chrboe** [comment] 2017-09-16 11:14
As `pass` is actually just a shell script, literally all it does when creating an n-length password is take all graphical symbols (bash's `[:graph:]` builtin) and extract n characters from a random position in the string (via `/dev/urandom`).
I haven't looked into it, but I'm pretty sure from a Golang perspective this is a trivial exercise to implement, which means we only need somebody worrying about the frontend.

**Comment by chrboe** [comment] 2017-09-16 11:16
*(I'd edit my comment, but GitHub's mobile interface is dumb)*

That said, I'd be happy to implement the back end of this issue, provided someone else looks into the context menu and stuff.

**Comment by bddenhartog** [comment] 2017-09-16 13:52
@chrboe I agree that it would likely be fairly simple to implement the same kinda of password generation -- I didn't mean to say that we couldn't, simply that we couldn't use `pass` to do so.

> GitHub's mobile interface is dumb)

Yeah! Not being able to react to, edit, or delete comments is the most infuriating part of GitHub's mobile experience.

**Comment by maximbaz** [comment] 2017-09-18 22:09
I'll close this as duplicate of #24 as that one has 10 times more :+1: (and likely more subscribers) - let's continue discussion there.

**Closed by maximbaz** 2017-09-18 22:09 UTC
Labels: enhancement
