### ISSUE TITLE
Doesn't autofill first try.

### ISSUE THREAD

**Issue by duffydack** [dannyvankooten/browserpass#132] opened 2017-09-15 13:43 UTC
Minor niggle.  Click lock icon, select website url, prompt for key decryption, no autofill.  Repeat steps with cached key, autofill works.

Archlinux, Chromium

**Comment by maximbaz** [comment] 2017-09-15 14:19
This is duplicate of #83 and has been already fixed on `master`. Subscribe to #83, I'm preparing a new release now, will publish it soon and post in that thread - just keep in mind, the new extension will only be published on github, I cannot update webstores #117.

**Closed by maximbaz** 2017-09-15 14:19 UTC
