### ISSUE TITLE
I can't seem to load any password

### ISSUE THREAD

**Issue by fdw** [dannyvankooten/browserpass#19] opened 2016-12-20 17:29 UTC
I installed the addon as described for Firefox, and it seems to start okay (no error messages, at least). However, it can't find a password for any site I tried, and not even after manually searching. Is there something I missed? Is there a schema I should use for the filenames?

**Comment by fdw** [comment] 2016-12-21 16:26
Every file has a "username: " line, so I expected it to simply work. The files are all named "folder/domainpart.gpg", for example "coding/github.gpg"

I tried to test the binary by itself by executing it and entering json via stdin:
```
./browserpass-linux62
{"domain": "mail"}
```
However, this fails. In debug.log, there is the following error: 
```
2016/12/21 17:25:03 invalid character 'm' looking for beginning of value
```

**Comment by xavierva** [comment] 2017-01-04 15:15
Hi same issue there and here is what my file looks lilke : 

`mypassworkd
username: fortest`

**Comment by emersion** [comment] 2017-01-04 21:44
@fdw It's not easy to test manually the binary as soon as it's expecting an uint32 LE containing the length of the JSON message before the message itself.

browserpass is supposed to search in any directory within the password store for a file begining with the query, so it's supposed to work. Can you try to add a password in the root and test if you can query it?

**Comment by fdw** [comment] 2017-01-05 08:41
@emerson: I copied one of my other passwords ("foo.gpg") to the top level directory of pass, installed the latest binary and Firefox addon, restarted, and then queried for the filename ("foo"). No results :(

However, I just noticed that I don't use the default directory for my passwords and set it using $PASSWORD_STORE_DIR. Could this be the problem?

**Comment by dannyvankooten** [comment] 2017-01-05 10:47
Hi @fwd,

That could very well be the source of the problem. The binary checks whether that environment variable is set and if not, it will assume the default pass directory of `~/.password-store`. If you set the `PASSWORD_STORE_DIR` environment variable then that will be used instead (make sure it's set for the user running the binary though).

**Comment by fdw** [comment] 2017-01-05 11:45
Hi @dannyvankooten,

I use my the directory "/home/me/.local/share/pass", and $PASSWORD_STORE_DIR is accordingly set (on login) to "/home/me/.local/share/pass" - so that seems correct. `pass` itself also works without problems.

I suppose the binary runs as the same user as firefox, so that shouldn't be the problem either. Is there any way to check that?

**Comment by dannyvankooten** [comment] 2017-02-10 12:29
Can you please try manually building the Browserpass binary with 343722bee3bfff3739caceee74d2a543505d8cd5 to see if that fixes anything? It invokes the gpg command directly instead of invoking pass.

If it still doesn't trigger the GPG agent, can you please invoke Chrome from the command line using:

```
google-chrome --enable-logging --v=1
```

That should enable logging and show all logging statements from Browserpass too which would be super helpful here. :)

**Comment by fdw** [comment] 2017-02-12 11:13
I'm sorry, I have no experience with go, and I seem to be missing a dependency. Is there anything else to do except the `go build` command from the makefile?

Also, I'm using Firefox, if that makes a difference.

**Comment by dannyvankooten** [comment] 2017-04-10 07:02
This is probably also a duplicate of #53, and has to do with the browser running as a different user without access to the required environment variables. We're still trying to work out how to properly fix this.

**Comment by fdw** [comment] 2017-04-10 07:27
According to `htop`, Firefox runs as my main user, where pass works.

**Comment by dannyvankooten** [comment] 2017-04-10 07:43
@fdw Is the browser extension able to retrieve passwords when you invoke Firefox from the command-line? Maybe "user" was a bit too specific in my wording, but it seems to have something to do with the browser running in isolation when not launched from the CL on OSX.

```
open -a Firefox
```

**Comment by fdw** [comment] 2017-04-10 07:51
I'll try to test it later today. Keep in mind, though, that I'm on Ubuntu :)

**Comment by fdw** [comment] 2017-04-13 18:22
I finally found time to test your hypothesis, and you're partially correct, @dannyvankooten - it worked when I started it from the terminal :)

However, the issue was not the different user (it was the same), but that I set the environment variable for the pass directory in my .zshenv file, and so it was only defined when I started it from the terminal.
I have fixed this now, and you can close this bug. Thank you very much! :)

**Comment by rafi** [comment] 2017-07-21 09:26
See [#13](https://github.com/dannyvankooten/browserpass/issues/13#issuecomment-316951512) for a solution with a wrapper that loads missing environment variables.

**Comment by maximbaz** [comment] 2017-09-14 18:31
I'll close the issue for cleanup purposes since it seems to be solved, let me know if it is not the case.

**Closed by maximbaz** 2017-09-14 18:31 UTC
Labels: bug, duplicate
