### ISSUE TITLE
Causes outdated browser message on discoverbank.com when autosubmit is enabled

### ISSUE THREAD

**Issue by ashkitten** [dannyvankooten/browserpass#227] opened 2018-03-21 15:44 UTC
### General information

* Operating system + version: Arch Linux (Linux 4.15.10-1-ARCH)
* Browser + version: Chromium 65.0.3325.162
* Information about the host app:
  * If installed via package manager or downloaded from [releases](https://github.com/dannyvankooten/browserpass/releases) page, put a release version: 2.0.12-1
	  * If in doubt what version you have, download and re-install the latest version!
  * If built from sources, put a commit id (`$ git describe --always`): 
* Information about the browser extension:
  * Browserpass extension version as reported by your browser: 2.0.13

---

### Exact steps to reproduce the problem
1. Enable autosubmit login forms in browserpass extension settings
2. Navigate to discoverbank.com
3. Click the login button to open the popup
4. Use browserpass to fill the form

### What should happen?
It should take you to the account page

### What happened instead?
It takes you to https://portal.discover.com/psv1/notification.html

**Comment by maximbaz** [comment] 2018-03-21 16:11
Wow, this is an interesting case. 

This is caused by #217, until now when a login button was not found we did nothing, but now as a fallback we try to submit the form natively.

First of all, why the login button is not being found on discoverbank.com? Because have a broken markup, they put the login button outside of the `<form>` 🤦‍♂️ .

And when we submit the form natively, discoverbank.com thinks that this happens because your browser is very old. Why? Probably because they listen on button press and do some extra steps, and when our extension is submitting the form it's not doing these actions.

#217 does more good than harm, it's a shame that this website defined a bad markup for their form and now it's trying to be smart and reject old browsers, but I don't see anything we can do.

**Comment by maximbaz** [comment] 2018-03-21 16:16
I'm not sure that you will like this workaround, but here it is: you can use a different "login page" of this bank, for example this page seems all right: https://portal.discover.com/customersvcs/universalLogin/signin

**Comment by ashkitten** [comment] 2018-03-21 16:18
Is there any hinting we could take advantage of to find the login button? Also that login page is only for discover credit

**Comment by maximbaz** [comment] 2018-03-21 16:20
It sounds very dangerous to guess and click buttons outside of the login form, who knows what they actually do, I'd rather make extension not submit a form than click a wrong button.

**Comment by maximbaz** [comment] 2018-03-21 21:20
I'll close this because I honestly don't see what we can do in this case, unfortunately. Consider reporting this issue to their support team, who knows, maybe they will fix the markup - it's as easy as moving the "login" button inside the form.

**Closed by maximbaz** 2018-03-21 21:20 UTC
