### ISSUE TITLE
Not pasting in Firefox on OSX

### ISSUE THREAD

**Issue by mcnesium** [dannyvankooten/browserpass#53] opened 2017-03-17 18:29 UTC
Steps to reproduce:

* use Firefox 52.0 (64bit) on OSX and pass
* install browserpass installed to `~/Applications/Browserpass/`
* run `./install.sh`
* install [Firefox extension](https://addons.mozilla.org/en-US/firefox/addon/browserpass/)
* go to a login form page in Firefox
* click the lock button -> browserpass detects the correct username/password combination
* click the password -> **the processing-wheel keeps spinning and no username or password will ever be entered in the login form**

It works perfectly with my Firefox 52 on Linux though.

**Comment by Spoons** [comment] 2017-03-19 02:29
This is an issue with all browserpass and OSX. It also happens with Chrome and Opera. As a work around you can open Firefox with `open -a Firefox` in the terminal and it should work.

**Comment by joyarzun** [comment] 2017-04-04 02:49
I could help with this, but don't understand why is happening

**Comment by dannyvankooten** [comment] 2017-04-10 07:01
Duplicate of #13, this has to do with the correct environment variables not being set when not launching Firefox from the command-line. We're still trying to work out how to best fix this.

**Closed by dannyvankooten** 2017-04-10 07:01 UTC
