### ISSUE TITLE
Add basic http authentication login

### ISSUE THREAD

**Issue by varac** [dannyvankooten/browserpass#123] opened 2017-08-20 19:21 UTC
It would be great if browserpass could support basic http authentication.
I didn't get it working.

**Comment by dannyvankooten** [comment] 2017-09-14 09:13
I doubt whether this is possible as there's probably no way for Browserpass to modify the authentication prompt but if someone knows a way, please correct me.

**Comment by maximbaz** [comment] 2017-09-14 14:37
In Chrome it is possible to fill-in basic auth prompt, but only if extension is the one who is opening a website. If you already see the browser popup, it is too late, extension cannot do anything.

So it requires implementing a completely different workflow for browserpass, besides the current "fill in \<these credentials\> on the currently opened page" we would need "open \<this link\> and fill in \<these credentials\>".

I'll close this as duplicate of #103, where I posted a few links on how to implement this a while ago.

**Closed** 2017-09-14 14:37 UTC
