### ISSUE TITLE
Subdomains not working

### ISSUE THREAD

**Issue by varac** [dannyvankooten/browserpass#79] opened 2017-05-14 20:48 UTC
I updated to 1.0.4, and now I notice that passwords for `DOMAIN.TLD` work but not for `SUB.DOMAIN.TLD`.
I'd like to debug/provide more info but even when starting `chromium-browser --verbose 2>&1 | grep -i pass`, I can't find any browserpass entries in the logs.

The only UI feedback I get is: `No passwords found for sub.domain.tld`

**Comment by mbretter** [comment] 2017-05-15 06:08
Similar problems here, many of my entries are not found anymore automatically after upgrading to 1.0.4 and even if I'm searching manually, entries are not found.

private/ebanking.foobar.com

=> searching "foo" no entries found
=> searching "ebank" entry was found

**Comment by joyarzun** [comment] 2017-05-15 16:17
This is happened for this #44 PR. Maybe, I could send a PR for add tests and fix it.

**Comment by dannyvankooten** [comment] 2017-05-15 20:01
Hey all, you're right, just noticed this myself earlier today as well. 

Looks like #44 introduced this. There are a few open PR's ( #61 #62 ) which improve on this already but we'll be reworking the search soon so it's a bit smarter when auto-searching & more specific when searching manually.

**Comment by joyarzun** [comment] 2017-05-17 13:34
@dannyvankooten this means that is better to wait or we can fix it now?

**Comment by dannyvankooten** [comment] 2017-05-22 12:00
Duplicate of #81, fixed in #82

**Closed by dannyvankooten** 2017-05-22 12:00 UTC
Labels: bug

**Comment by varac** [comment] 2017-05-28 09:20
@dannyvankooten Could you do a relase based on this PR pls ? 80% of my logins doesn't work anymore for me (and I guess roughly the same amount for everybody else), so I consider this a severe bug that should be covered by a hotfix release.

**Comment by joyarzun** [comment] 2017-05-28 14:32
I had to install master branch base plugin. It's not the best at all, but if there is not a release soon is better than nothing.
