### ISSUE TITLE
Autofill truncates password on ! character

### ISSUE THREAD

**Issue by tadfisher** [dannyvankooten/browserpass#125] opened 2017-09-07 18:43 UTC
One of my passwords has a `!` character in the middle. When filling via browserpass, the password is truncated at this character.

For example, a pass entry with the following contents:

```
qwerty!uiop
```

Fills a password field with the following:

```
qwerty
```

**Comment by maximbaz** [comment] 2017-09-15 10:33
@tadfisher I tried your exact pass entry `qwerty!uiop` on github login page, and it is not being truncated. Could you provide a particular website where this is reproducible?

**Comment by chrboe** [comment] 2017-09-15 16:20
What OS/Browser are you using? @tadfisher

**Comment by maximbaz** [comment] 2017-09-27 21:49
Closing as unable to reproduce, let me know if this is still an issue on the latest browserpass, and make sure to post the specific webpage where we can confirm the bug.

**Closed by maximbaz** 2017-09-27 21:49 UTC
Labels: bug, question
