### ISSUE TITLE
Feature: Specify a path to search for

### ISSUE THREAD

**Issue by Soullivaneuh** [dannyvankooten/browserpass#184] opened 2017-10-17 15:32 UTC
With the following pass structure:

```
Password Store
├── github
│   ├── Soullivaneuh.2fa
│   └── Soullivaneuh
├── gitlab
│   ├── gitlab.com
│   │   ├── Soullivaneuh.2fa
│   │   └── Soullivaneuh
├── nas
│   └── slenderman
└── web
    ├── console.web.net
    │   └── toto
    ├── awesome.com
    │   └── toto
    └── private.net
        └── toto

```

I would like the browserpass plugin to look at the `web` directory and only this once.

I think this can be ended with a plugin option.

This best would be to have this options synced on Chrome.

**Comment by maximbaz** [comment] 2017-10-17 16:05
This is a duplicate of #34, please upvote that one and subscribe to it 🙂

**Closed by maximbaz** 2017-10-17 16:05 UTC

**Comment by Soullivaneuh** [comment] 2017-10-19 08:08
Oh right, I didn't see this one, thanks! :+1:
