### ISSUE TITLE
browserpass && GnuPG-card needs a second click after entering the PIN

### ISSUE THREAD

**Issue by gurucubano** [dannyvankooten/browserpass#104] opened 2017-07-07 09:29 UTC
I'm using behind browserpass the GnuPG-card and to allow access to the secretkey, one must enter a 6 digit PIN. The card then remains unlocked until withdraw. When I need some web credentials in the first time after card insert, the click on the browserpass icon let me select the correct keyfile from password-storage and the request results in a PIN-entry pop-up which unlocks the secret fine. But, the credentials are not written into the browser fields. It need a second click on the icon to get them now written correctly.

Is there anything I could debug to help?

Matthias

**Comment by maximbaz** [comment] 2017-07-08 09:13
The issue is more generic, and it's a duplicate of #83 (also #86 and #87)

**Comment by maximbaz** [comment] 2017-09-14 18:37
This has been fixed in `master` branch, thus closing for cleanup purposes.

**Closed by maximbaz** 2017-09-14 18:37 UTC
