### ISSUE TITLE
broken on Firefox + OpenBSD

### ISSUE THREAD

**Issue by bonds** [dannyvankooten/browserpass#113] opened 2017-07-26 20:38 UTC
I'm running BrowserPass 1.05 on Firefox 52.0.2 on OpenBSD 6.1-stable amd64. When I click on the UI button, I see ````Error talking to Browserpass host```` and in the browser console I see:

````
cannot read contents of null pointer ctypes.char.ptr.ptr(ctypes.UInt64("0x0"))  NativeMessaging.jsm:216
    this.NativeApp</this.startupPromise< resource://gre/modules/NativeMessaging.jsm:216:9
Error: Attempt to postMessage on disconnected port  script.js:98:4
````

**Comment by bonds** [comment] 2017-07-26 21:31
BTW, browserpass works fine on Chromium + OpenBSD 6.1-stable amd64.

**Comment by qbit** [comment] 2017-09-18 12:26
@bonds can you grep "Browserpass" from ~/.xsession-errors (if you are starting X via xenodm or similar)? Also are FF and Chromium using the same binary? Can you run "echo asdfasdf | ./browserpass" for each one (or single, if they are both using the same bin)?

**Comment by qbit** [comment] 2017-09-18 16:59
NM, I am able to reproduce.

**Comment by qbit** [comment] 2017-09-18 23:13
Looks like this is a bug with firefox: https://dxr.mozilla.org/mozilla-central/source/toolkit/components/extensions/NativeMessaging.jsm#61,65

**Comment by maximbaz** [comment] 2017-09-18 23:21
This explains why it works on other platforms... 

Will you file a bug for them? Since it's nothing we can do here, I'd rather close this issue and subscribe to the Firefox bug.

**Comment by maximbaz** [comment] 2017-09-27 21:52
Closing since it doesn't look like something we can do on our side. Feel free to add here a tracking bug for Firefox, or reopen if you have some ideas on how we can solve it here 🙂

**Closed by maximbaz** 2017-09-27 21:52 UTC
Labels: bug, help wanted
