### ISSUE TITLE
Mac OS Keyboard Hotkeys should use Ctrl

### ISSUE THREAD

**Issue by mcnesium** [dannyvankooten/browserpass#51] opened 2017-03-16 13:53 UTC
When on a login page the user input field is focused right away (which is good) and I hit `Alt+Shift+L` to open up the browserpass popup, it does not do so but writes a *ﬂ* to the user input field, as `Alt` is the third layer keyboard switch in OSX. So for the browserpass hotkey on the Mac `Ctrl+Shift+L` would work better, I guess. Or an option to make it configurable, in `user.js` for example.

**Comment by maximbaz** [comment] 2017-03-20 16:28
I dislike <kbd>Alt+Shift+L</kbd> for a different reason: often <kbd>Alt+Shift</kbd> is used to toggle keyboard language, so together with opening a popup I change the language. 

The good thing is that in Chrome you can modify the hotkey on this page: chrome://extensions/configureCommands

![image](https://cloud.githubusercontent.com/assets/1177900/24109965/819d907c-0d92-11e7-8c6d-e91b0cfa203a.png)

**Comment by dannyvankooten** [comment] 2017-04-10 06:58
Relates to #60

**Comment by maximbaz** [comment] 2017-09-14 19:15
I'll close this as duplicate of #60 for cleanup purposes.

**Closed by maximbaz** 2017-09-14 19:15 UTC
Labels: enhancement
