### ISSUE TITLE
Add support for gopass

### ISSUE THREAD

**Issue by SevereOverfl0w** [dannyvankooten/browserpass#126] opened 2017-09-12 07:10 UTC
Gopass is a pass-compatible implementation which adds new features. https://github.com/justwatchcom/gopass

Basic support is in allowing selection of `gopass` as command to execute.

Full support is in using `gopass ls --flat` in order to list passwords, which will then cover a particular gopass feature called "mounts"

**Comment by maximbaz** [comment] 2017-09-14 22:31
Hey @SevereOverfl0w, `browserpass` is not using `pass` as a binary for [a number of reasons](https://github.com/dannyvankooten/browserpass/issues/6), it is using `gpg` directly to decrypt the files. Since `gopass` is backwards-compatible, I suppose basic support should already be in place.

Now supporting "mounts" is an interesting case, it will definitely not work out of the box as this is a different folder in the file system. I would like to hear other's ideas on how to best add support for these.

Is there anything in particular that you would like to be supported from gopass, besides mounts?

**Comment by maximbaz** [comment] 2017-09-27 21:48
Closing as duplicate of #77, if you have additional requests for specific `gopass` features, please create separate issues for them.

**Closed by maximbaz** 2017-09-27 21:48 UTC
Labels: question
