### ISSUE TITLE
I have to press twice

### ISSUE THREAD

**Issue by joyarzun** [dannyvankooten/browserpass#83] opened 2017-05-26 02:13 UTC
In the first time gpg ask me for a password, okay I enter it but nothing happened. Then I have to press browserpass again to fill the form.

Browserpass version: Master branch (1.0.4)
OS: MacOs
Browser: Opera last and Chrome 58

**Comment by maximbaz** [comment] 2017-05-27 20:40
Yes, I see this as well. The first time the key is being added to gpg-agent but after action stops, the second time the key is already in the agent so password is successfully retrieved.

**Comment by raxod502** [comment] 2017-05-31 00:38
This issue happens for me because my pinentry program (pinentry-mac) creates and focuses a new window, which causes the browserpass dropdown menu to lose focus and disappear. This could be resolved by making the dropdown menu less eager to disappear as soon as it loses focus.

**Comment by joyarzun** [comment] 2017-05-31 02:41
Do you know why this happen with mac pinentry and do not with others like linux pinentry? For example, I work with Manjaro Gnome flavor and the issue does not occur. Anyway, do you figure out how to work around?

**Comment by raxod502** [comment] 2017-05-31 02:53
Presumably it's a difference in how the window manager handles window focusing. I can't test on macOS, since all other pinentry programs are horribly broken for me. There is no workaround that I can see other than just entering my password twice (since gpg-agent will cache it).

Aside from it causing this issue, I think the fragility of the popup is a bug in its own right, since I frequently am interrupted in the middle of an operation and don't want whatever I'm working on to disappear on me.

**Comment by jayme-github** [comment] 2017-06-19 07:18
Happens for me too:
OS Linux
pass 1.7.1
browserpass 1.0.6
chrome 59

Seems like i'ts not an easy task to prevent the addon from closing when using focus (https://stackoverflow.com/questions/4146930/how-to-keep-google-chrome-extension-popup-open). 
Maybe it is possible for the addon to complete it's work even when closed? (Must admit that I have almost no idea about addon development for both chrome and firefox).

**Comment by joyarzun** [comment] 2017-06-19 14:28
@jayme-github It doesn't happen to me in Linux. Can you change your pinentry?

**Comment by jayme-github** [comment] 2017-06-19 15:16
@joyarzun I probably can - which do you use?
Mine is pinentry-gnome3 currently... (running a KDE5 environment this seems pretty odd :smile: )

**Comment by mlen** [comment] 2017-07-01 16:18
Happens for me with `pinentry-gtk-2`

**Comment by mlen** [comment] 2017-07-02 17:40
Another thing is that this may depend on the window manager being used, for me it is awesomewm 4.0

**Comment by jayme-github** [comment] 2017-07-03 10:26
I'm not completely sure with this (and failed badly trying :-)) but maybe we could work around this by using a separate event page/background script kind of thing (at least in chrome) that does the native messaging and runs the script in tab context.
https://developer.chrome.com/extensions/event_pages

What I got that right (and it's perfectly possible I'm not) the event page should be able to complete the work even if the focus on the popup is gone.

**Comment by joyarzun** [comment] 2017-07-03 15:53
@jayme-github @mlen 
```
$ cat ~/.gnupg/gpg-agent.conf
pinentry-program /usr/bin/pinentry-gnome3
```

![listopeek 2017-07-03 11-22](https://user-images.githubusercontent.com/828211/27800130-14710f8c-5fe6-11e7-920c-b9bff1855ccf.gif)

**Comment by maximbaz** [comment] 2017-07-03 16:36
I've just tried pinentry-gtk2, pinentry-gnome3 and pinentry-qt, the result is always the same, popup gets closed as soon as pinentry dialog appears.

Feels like your WM is not sending some kind of "focus lost" signal to Chrome when pinentry dialog appears, while our WMs do that and that's why popup gets closed. I'm on i3wm.

**Comment by joyarzun** [comment] 2017-07-03 16:56
I have Arch Linux, Gnome flavor. With all pretty standard, I think.

**Comment by cstroe** [comment] 2017-07-14 06:52
Seeing this issue with:
* WM: Xfce 4.12
* OS: FreeBSD 11.0.1
* Pinentry: pinentry-gnome3
* Browser: Firefox 54.0.1

First click shows the pinentry dialog, but doesn't fill in the password.  Second click fills in password and logs in.

**Comment by joyarzun** [comment] 2017-07-14 13:46
Now happen to me the same issue with Manjaro Deepin Desktop:

WM: Deepin 15.x
OS: Arch Linux
Pinentry: pinentry-gnome3, pinentry, pinentry-qt
Browser: Chromium

**Comment by aventrax** [comment] 2017-08-02 18:13
same here on gnome and windows. So there isn't a solution right now...can we hope to have this solved?

**Comment by muesli** [comment] 2017-08-22 22:18
Same here on latest Arch with Plasma and Chromium.

**Comment by maximbaz** [comment] 2017-09-13 18:38
@irtimmer fixed this issue in #119, works like a charm 🎉

**Comment by maximbaz** [comment] 2017-09-13 18:39
@dannyvankooten you aren't very active these days in this repo, while the issues like this or #101 are really painful, and community has already implemented the fixes. I started merging PRs in my own fork, so at least we have a version _somewhere_ with important fixes all in one place... but it isn't as easy for others to use as merging PRs in this main repo. 

So, if you want, I'm willing to co-maintain / take over this project, e.g. doing code reviews and merging outstanding PRs. Let me know!

**Comment by dannyvankooten** [comment] 2017-09-14 08:42
@maximbaz Sorry about that, I'm in the mids of moving between houses and expecting our first child in October so definitely a little too busy to be looking at Browserpass. I have just added you as a collaborator for the repository. Thanks for the help!!

**Comment by maximbaz** [comment] 2017-09-14 08:45
Congratulations :) What is the best way to organize publishing chrome extension and AUR packages, could you grant me somehow collaboration permissions there as well?

**Comment by maximbaz** [comment] 2017-09-14 18:35
I'll close the issue since it has been fixed in `master`, and will deal with packing extension separately.

**Closed by maximbaz** 2017-09-14 18:35 UTC

**Comment by maximbaz** [comment] 2017-09-15 14:33
I've just published a github release v1.0.8. Could someone give it a try? Let me know both if the issue is fixed and how the upgrade went, i.e. did your browser complain on extensions compiled by me instead of Danny or not.

**Comment by mlen** [comment] 2017-09-15 17:42
@maximbaz any chance of releasing it to chrome webstore?

**Comment by maximbaz** [comment] 2017-09-15 17:52
I really wish I could @mlen, but I have neither `.pem` file to sign the packages nor access to webstore to actually update them. Only @dannyvankooten has these, so only he can push updates to webstore.

Subscribe to #117 and you will get notification when webstore is updated.

I guess if there will be no answer from Danny for a while, we'll have to publish the packages to the webstore under a different name.
