### ISSUE TITLE
Browser extensions in Webstore are out of date

### ISSUE THREAD

**Issue by tanderson92** [dannyvankooten/browserpass#117] opened 2017-08-11 21:52 UTC
The browserpass page shows the latest version as 1.0.5.: https://chrome.google.com/webstore/detail/browserpass/jegbgfamcgeocbfeebacnkociplhmfbk

But the latest version is 1.0.6.

**Comment by maximbaz** [comment] 2017-09-15 00:26
Same goes for Firefox - we cannot do this without @dannyvankooten.

**Comment by maximbaz** [comment] 2017-09-29 20:43
[v2.0.0](https://github.com/dannyvankooten/browserpass/releases/tag/2.0.0) was just released in [Chrome](https://chrome.google.com/webstore/detail/browserpass-ce/naepdomgkenhinolocfifgehidddafch) and [Firefox](https://addons.mozilla.org/en-US/firefox/addon/browserpass-ce/) webstores!

These are the new extensions, rebranded as **Browserpass - Community Edition**, so you have to remove the old ones if you still have them installed.

Enjoy 🙂

**Closed by maximbaz** 2017-09-29 20:43 UTC

**Comment by chrboe** [comment] 2017-09-29 20:45
This is the most satisfying thing, seeing all of these issues being resolved 🙂 Thanks for the release Maxim!

(As a side note, we should probably still take care to maintain backwards compatibility with the old extension, since a lot of people will still be using that)

**Comment by maximbaz** [comment] 2017-09-29 20:57
I made the host app incompatible with the old extension, and I did it on purpose, as there is no excuse not to upgrade frontend if one is upgrading the host app to v2 😛 

It is a one-time action anyway, future updates will be pushed via Webstore automatically. Furthermore, we have the `chrome-policy.json` back, meaning that Chrome extension is installed automatically from the store (no luck for Firefox... and for Windows users, for now - #163)

**Comment by chrboe** [comment] 2017-09-29 21:05
I don't know, I just don't like the idea of it silently failing because of an upgrade (many people won't even be aware of the new extension name).

I assume it just fails with `Error talking to browserpass host` now, right? My concern is primarily that people will be filing hard-to-debug errors caused by the upgrade that just say "it doesn't work". Though I guess we could figure it out if they manage to report their versions correctly 🤔 

I guess there's not much we can do about it anyways, it's not like we can change the old extension (to display an appropriate error) 🤷‍♂️.

Speaking of errors: I know this is getting off topic, but how about reporting more verbose errors to the UI in general? 🙂

**Comment by maximbaz** [comment] 2017-09-29 21:20
I think it is worth the risk, it's a temporary inconvenience that has lots of long-term benefits for everyone. But the concern is valid, and I hope it will be at least partially handled by this ticket with catchy title that I'll leave open for a couple of weeks: #165.

Speaking of errors handling, let's discuss it separately - in #164.

**Comment by tanderson92** [comment] 2017-09-30 00:04
Thank you very much Maxim! The new shortcut behavior seems acceptable too.

The "Find more username fields" feature is welcome and seems to improve some sites. Thanks! Unfortunately it's still broken on citi.com, which is only a very minor inconvenience.

**Comment by maximbaz** [comment] 2017-09-30 10:46
@tanderson92 I fixed the citi.com support in https://github.com/dannyvankooten/browserpass/commit/4cf2dae69bbcfd83700fd3889470ae1ef57bf424 - will be a part of 2.0.1 release 😉 

Note for everyone: do not hesitate opening new issues for sites where browserpass doesn't fill passwords in, [sometimes](https://github.com/dannyvankooten/browserpass/issues/156) we cannot do anything about it, but sometimes it is really useful, investigating citi.com actually brought up two major improvements to the detection algorithm, which will improve other websites too (details in the commit message for those of you who are interested).
