### ISSUE TITLE
Cygwin support

### ISSUE THREAD

**Issue by DancingQuanta** [dannyvankooten/browserpass#25] opened 2017-01-06 09:25 UTC
Hi I wanted to ask if it is possible to for `browserpass` to work on Windows using Cygwin as a bash shell?

**Comment by emersion** [comment] 2017-01-06 10:01
Also see #6.

**Comment by DancingQuanta** [comment] 2017-01-08 11:13
i could use a python host, which I have contributed to, for a similar [extension](https://github.com/DancingQuanta/chrome-pass) that does not use `pass` but I would like to see documentation of native messaging between browserpass extension and host as the browsepass extension is more interesting than the one I mentioned.

**Comment by wiktor-k** [comment] 2017-01-20 13:51
@DancingQuanta I'm not the author but after code-reading and writing alternative backend application the protocol is quite simple:

For searching the extension sends this JSON:

```js
{ "action": "search", "domain": "..."}
```

And expects in response an array of strings (in the UI each string will be a position on the list).

When the user selects something on the list the extension sends:

```js
{ "action": "get", "entry": "...selected-domain" }
```

And expects a response:

```js
{ "u": "...username", "p": "...password" }
```

Hope that helps!

**Comment by wiktor-k** [comment] 2017-01-20 14:50
@DancingQuanta If you'd like my Python script you can get this extension running on Windows & Firefox like that:

1. Put the Python script somewhere (`quickpass.py`):
```python
#!/usr/bin/env python

import struct
import sys
import subprocess
import json
import base64
import glob
from os.path import expanduser

root = expanduser("~") + "/.password-store/"

def read():
    rawlen = sys.stdin.read(4)
    if len(rawlen) == 0:
        sys.exit(0)
    msglen = struct.unpack('@I', rawlen)[0]
    msg = sys.stdin.read(msglen)
    return json.loads(msg)

def write(msg):
    encmsg = json.dumps(msg)
    sys.stdout.write(struct.pack('@I', len(encmsg)))
    sys.stdout.write(encmsg)
    sys.stdout.flush()

while True:
    body = read()
    if body['action'] == 'search':
        write(map(lambda x: x[len(root):-4], glob.glob(root + "**/*.gpg") + glob.glob(root + "*.gpg")))
    elif body['action'] == 'get':
        pipe = subprocess.Popen(["gpg", "--decrypt", root + body['entry'] + '.gpg'], stdout=subprocess.PIPE)
        stdout, stderr = pipe.communicate()
        if pipe.returncode == 0:
            lines = stdout.split("\n")
            password = lines[0]
            properties = { }
            for line in lines[1:]:
                parts = line.split(": ", 1)
                properties[parts[0]] = parts[1] if len(parts) > 1 else ''
            write({
                'p': password,
                'u': properties.get('login') or properties.get('user') or properties.get('username')
            })
        else:
            write({
                'error': 'could not retrieve password'
            })
```
2. Create bat file (`quickpass.bat`) with contents: `@python absolute-path-to-quickpass.py`
3. Create JSON manifest:
```json
{
  "name": "com.dannyvankooten.browserpass",
  "description": "Retrieves GPG encrypted passwords",
  "path": "path-to-bat-file-from-step-2",
  "type": "stdio",
  "allowed_extensions": ["browserpass@dannyvankooten.com"]
}
```
4. Register using this command: `REG ADD "HKEY_CURRENT_USER\SOFTWARE\Mozilla\NativeMessagingHosts\quickpass" /ve /d "path-to-quickpass.json" /f`
5. I've used the browser extension from Releases and importing it locally. Unfortunately the official extension from AMO is marked as Linux/MacOS only.

Manifest and registration are similar for Chrome and this script should work cross-platform. It works with GPG Agent and smartcards.

Have fun!

**Comment by soren121** [comment] 2017-05-13 21:40
The script provided by @wiktor-k works for me, but the registry add command isn't correct (at least, if you're using the Browserpass extension as-is.) For anyone else trying this, it should be this: 

`REG ADD "HKEY_CURRENT_USER\SOFTWARE\Mozilla\NativeMessagingHosts\com.dannyvankooten.browserpass" /ve /d "path-to-quickpass.json" /f`

On Windows, the name of the registry key has to match the `name` field in the manifest file, [according to MDN](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_messaging#App_manifest). Otherwise, you'll get an error that says "This extension does not have permission to use native application..."

**Comment by wiktor-k** [comment] 2017-05-14 13:34
Oh, you're right @soren121 I was experimenting with different package name and forgot to update the comment.

Thanks for the correction!

**Comment by aventrax** [comment] 2017-07-04 07:41
Hello. I'm trying to use this script on FF (windows 10), but the extensions keep saying "Error Talking to browserpass host".
I do not know how to have a log of the error. I tried with the Firefox "Debug Extension" but It's confusing for me...

C:\Users\user\AppData\Roaming\passff\test.json
`
{
  "name": "com.dannyvankooten.browserpass",
  "description": "Retrieves GPG encrypted passwords",
  "path": "C:\Users\user\AppData\Roaming\passff\test.bat",
  "type": "stdio",
  "allowed_extensions": ["browserpass@dannyvankooten.com"]
}
`

REG ADD "HKEY_CURRENT_USER\SOFTWARE\Mozilla\NativeMessagingHosts\com.dannyvankooten.browserpass" /ve /d "C:\Users\user\AppData\Roaming\passff\test.json" /f


C:\Users\user\AppData\Roaming\passff\test.bat
`
@python C:\Users\user\AppData\Roaming\passff\test.py
`

C:\Users\user\AppData\Roaming\passff\test.py
`...your script...`


How can I make it working? I've tried with chrome but the results is almost the same, help!

**Comment by aventrax** [comment] 2017-07-04 12:44
Really, no way. I tried the other extension: chrome-pass and the extension can communicate through the python script, indeed I can see my password-store entries.
No luck with your script, configured the same way, tried with FF, chrome, iridium.... it results in "Error Talking to browserpass host".... no matter what I try.
I can't debug it, I don't know how to force FF to show me the error it has...

**Comment by aventrax** [comment] 2017-07-04 15:34
Finally some debug...


`stderr output from native app com.dannyvankooten.browserpass: Traceback (most recent call last):
stderr output from native app com.dannyvankooten.browserpass:   File "C:\Users\user\Downloads\browserpass\browserpass.py", line 28, in <module>
stderr output from native app com.dannyvankooten.browserpass:     body = read()
stderr output from native app com.dannyvankooten.browserpass:   File "C:\Users\user\Downloads\browserpass\browserpass.py", line 17, in read
stderr output from native app com.dannyvankooten.browserpass:     msglen = struct.unpack('@I', rawlen)[0]
stderr output from native app com.dannyvankooten.browserpass: TypeError: a bytes-like object is required, not 'str'`

**Comment by soren121** [comment] 2017-07-04 18:19
@aventrax To debug on the Firefox side, you have to first enable add-on debugging, and then all errors will be redirected to the browser console.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Debugging#Viewing_log_output

Also, I think I've encountered that Python error before. Try running the script with Python 2.7 instead of Python 3.

**Comment by aventrax** [comment] 2017-07-05 07:57
@soren121 Many many thanks! I used Python 2.7 and everything is fine. Woooh... too many hours lost for this ...

**Comment by maximbaz** [comment] 2017-09-14 19:08
Judging by https://github.com/dannyvankooten/browserpass/commit/c6736a999ae0932c7907b2b4108a6a3473806f4b, someone has it working on Windows, /cc @chrboe

So I want to ask you guys a few questions, just to clarify things for myself:

1. Is this issue about adding support for Windows, or about Cygwin specifically?
2. Is there anything actionable that someone might be able to contribute here, or you are happy with the proposed solution above? From what I understand, that python script is a reimplementation of go backend in python - is it needed because it is impossible to compile with `go` on Windows, or why?

**Comment by chrboe** [comment] 2017-09-14 19:19
After the changes of the referenced PR it worked on my Windows installation. I basically did the following:

1. Install MinGW
2. Install golang
3. Compile the go program as usual (not I'm not sure anymore, but I think a simple `go build` did the job)
4. Install the browser extension + manifest shenanigans

IIRC there was no black magic involved whatsoever.

*Please do note that this PR is a few months already, so I might not be able to recall all issues off the top of my head*

**Comment by wiktor-k** [comment] 2017-09-15 08:41
@maximbaz IIRC the browserpass go binary used to rely on `pass` to work. It was easier to just reimplement the minimal logic of pass and go binary in Python than to work on getting both `pass` and the go binary to work on Windows.

**Comment by maximbaz** [comment] 2017-09-15 08:44
I see, thanks! So is this issue obsolete now and can be closed, since `pass` binary is not used anymore and windows seems to be supported as per above?

**Comment by aventrax** [comment] 2017-09-15 08:48
I have the @wiktor-k script working on windows but I'm waiting to be able to use browserpass go executable...

**Comment by chrboe** [comment] 2017-09-15 08:51
Would you look at that, apparently I summarized the installation instructions in a gist once. I completely forgot about that, here it is: https://gist.github.com/chrboe/88bd52839c63f039825668547d0c5d38#step-4-browserpass (disclaimer: no idea whether or not this actually works (anymore), but I guess it should)

**Comment by chrboe** [comment] 2017-09-15 08:57
@wiktor-k It says that the manifest file should be in the same directory as `browserpass.exe`, however an absolute path would be safer anyways I guess...

You know what, I'll just test the setup with the latest binary package just so we can be sure here. I have yet to set up browserpass on my work PC anyways 😄

**Comment by chrboe** [comment] 2017-09-15 09:29
Alright folks, just got it running no problem.

For reference, here are my exact steps:
0. Setup go, gpg, git, and your password store (see gist for details)
1. Open Git Bash
2. Run `go get -t github.com/dannyvankooten/browserpass`
3. Figure out where your GOPATH is (I think default is `%homepath%/go`?)
4. Navigate to `$GOPATH/src/github.com/dannyvankooten/browserpass`
5. `go build -o browserpass.exe ./cmd/browserpass/`
6. Move `browserpass.exe` to a directory like `C:\browserpass` (path is irrelevant, it's just personal preference)
7. Copy the file `chrome/host.json` from the browserpass source to the **same directory `browserpass.exe` is in** and rename to `manifest.json`.
8. Open up the file and replace `%%replace%%` with `browserpass.exe`
9. Open up a regular cmd prompt (**NOT** Git Bash)
10. Execute `REG ADD "HKCU\Software\Google\Chrome\NativeMessagingHosts\com.dannyvankooten.browserpass" /ve /t REG_SZ /d "C:\browserpass\manifest.json" /f`
    (Pay attention to the path at the end if you've put your `browserpass.exe` somewhere else)
11. Fire up Chrome, the extension should now work

**Comment by maximbaz** [comment] 2017-09-15 09:48
Thank you for testing this! Then I think it is safe to close the issue.

@chrboe or anyone else, if you want to put these instructions in the README.md, do not hesitate to send a PR with a section for installation on Windows, I think it could be valuable.

**Closed by maximbaz** 2017-09-15 09:48 UTC
Labels: question

**Comment by aventrax** [comment] 2017-09-15 10:31
@maximbaz I compiled browserpass.exe successfully, but I have my pass folder on another location, so it came up with an error. I'm back to the script provided by @wiktor-k, so I can put `root = "R:/.password-store/web/"` :-)

**Comment by maximbaz** [comment] 2017-09-15 10:35
If I understood you correctly, you could define an environment variable `PASSWORD_STORE_DIR` pointing to the correct location of your password store, and the browserpass.exe will use it.

**Comment by chrboe** [comment] 2017-09-15 10:35
Sure thing, will do. What do you think the project's position on this should be? I'm guessing Windows isn't **officially** supported but rather experimental or something, right?

**Comment by maximbaz** [comment] 2017-09-15 10:41
I guess yes, it is correct to say that Windows isn't officially supported because scripts like `install.sh` just don't work on Windows. 

`Community has managed to get browserpass to work on Windows with the following steps` is something I would probably say 🙂

**Comment by aventrax** [comment] 2017-09-15 11:05
@maximbaz Ok, I set the PASSWORD_STORE_DIR variable and now it find my archive. Anyway, something is broken; the firefox extension compile only the password and not the username that should be derived by the file path (/web/google.com/myuser@google.com --> username myuser@google.com).
I'm now on windows but I have browserpass on linux too, and the username is filled into every form.

So:
1) Script by @wiktor-k on windows -> working
2) browserpass on Linux (compiled a couple of months ago) -> working
3) browserpass on windows (compiled today) -> non filling username.

The structure is the same: /web/my.site.com/username and my .gpg file contains only the password.
If I modify the .gpg file putting "login:username" before the password, it works even with browserpass on windows.

Can you help me? Why the "login:..." is needed now?

**Comment by chrboe** [comment] 2017-09-15 11:16
@aventrax I can reproduce this. Please create a separate issue.

**Comment by wiktor-k** [comment] 2018-03-20 11:42
If anyone's using the Python version (for any reason), I've extracted the script to a separate repo: https://github.com/wiktor-k/quickpass and fixed compatibility with new version of the extension (`match_domain` instead of `search` action).

**Comment by maximbaz** [comment] 2018-04-20 20:00
In case anyone is still using any kind of wrappers instead of our golang native host, please be aware that we rewriting the host app and it will have a different set of available actions and responses. Your wrapper will stop working with browserpass v3 unless you adapt your code.

[This document](https://github.com/browserpass/browserpass-native/blob/master/PROTOCOL.md) describes the new protocol: the list of actions, the structure of requests and responses, the list of error codes, etc.

However, instead of adapting your wrappers I encourage sharing your reasons for using the wrapper, so that we can incorporate these ideas in the new host app and you don't have to use your own wrappers. 

For example, the above comments mentioned the need for a custom location of `gpg` binary (the new host app allows configuring it) and custom location for password store (the new host app allows using one or more password stores in any location).

**Comment by wiktor-k** [comment] 2018-04-20 20:15
@maximbaz thanks for taking time to describe breaking changes and the protocol.

How does the native app get updated usually? I think it's not shipped with the extension and would need manual update.

For me there were two reasons why I used Python: 1. did not work on Windows (that's already solved) 2. I needed fuzzy matching in searches as my folder hierarchy is different than "suggested". I think now browserpass have fuzzy match option so I may try out the built-in host app.
